server:
  port: 5555
eureka:
  instance:
    prefer-ip-address: true   # 서비스 이름 대신 IP 주소 등록
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/
    register-with-eureka: true    # 유레카 서버에 서비스 등록
    fetch-registry: true          # 레지스트리 정보를 로컬에 캐싱
    registry-fetch-interval-seconds: 3    # 서비스 목록을 3초마다 캐싱